/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import java.util.Arrays;
import java.util.List;

public class PoetWithEcho implements IPoet {
    Poem poem;

    PoetWithEcho(Poem poem) {
        this.poem = poem;
    }

    @Override
    public String recite(Parser parser) {
        String recite = "";
        for (int index = 1; index <= parser.day; index++) {
            recite = recite + "Day " + index + " -";
            recite = recite + revealForTheDay(index) + "\n\t\n";
        }
        return recite.trim();
    }


    public String revealForTheDay(int day) {
        String recitePhrase = "This is ";
        String echoString;
        for (int index = day - 1; index >= 0; index--) {
            echoString = poem.lines.get(index);
            if (index == 0) {
                recitePhrase = recitePhrase + echoString + "\n\t" + echoString + ".";
                return recitePhrase.trim();
            }
            recitePhrase = recitePhrase + echoString + "\n\t" + echoString + "\n\t";
        }
        return recitePhrase.trim();
    }


}

